# this private module was removed in 1.15
# pyrefly: ignore [missing-import]
import scipy.misc._common  # type: ignore[import-not-found]  # pyright: ignore[reportMissingImports]

# ensure there are no 1.14 remnants left:
from scipy.misc import common, doccer

# pyrefly: ignore [missing-attribute]
common.__all__  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
# pyrefly: ignore [missing-attribute]
common.central_diff_weights  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
# pyrefly: ignore [missing-attribute]
common.derivative  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
# pyrefly: ignore [missing-attribute]
common.ascent  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
# pyrefly: ignore [missing-attribute]
common.face  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
# pyrefly: ignore [missing-attribute]
common.electrocardiogram  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]

# pyrefly: ignore [missing-attribute]
doccer.__all__  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
# pyrefly: ignore [missing-attribute]
doccer.docformat  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
# pyrefly: ignore [missing-attribute]
doccer.inherit_docstring_from  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
# pyrefly: ignore [missing-attribute]
doccer.indentcount_lines  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
# pyrefly: ignore [missing-attribute]
doccer.filldoc  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
# pyrefly: ignore [missing-attribute]
doccer.unindent_dict  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
# pyrefly: ignore [missing-attribute]
doccer.unindent_string  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
# pyrefly: ignore [missing-attribute]
doccer.extend_notes_in_docstring  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
# pyrefly: ignore [missing-attribute]
doccer.replace_notes_in_docstring  # type: ignore[attr-defined]  # pyright: ignore[reportAttributeAccessIssue, reportUnknownMemberType]
